id = "melange"
name = "Melange Theme"
version = "0.0.1"
schema_version = 1
authors = ["adorabilis"]
description = "A warm and cozy theme for Zed with dark and light variants"
repository = "https://github.com/adorabilis/melange-zed"
themes = ["themes/melange.json"]
languages = []

[lib]

[grammars]

[language_servers]
